### ISSUE TITLE
Show and Read instances for RE

### ISSUE THREAD

**Issue by cdepillabout** [iconnect/regex#146]
It would be nice to have `Show` and `Read` instances for [`RE`](https://hackage.haskell.org/package/regex-with-pcre-1.0.1.3/docs/Text-RE-PCRE.html#t:RE).

These instances probably shouldn't be used in any sort of production code, but they would be nice to have for debugging.

I'm not sure the best way to implement them, but even something just like directly calling [`reSource`](https://hackage.haskell.org/package/regex-with-pcre-1.0.1.3/docs/Text-RE-PCRE.html#v:reSource) would be better than nothing.

It looks like other types like `Matches`, `SearchReplace`, etc, all have at least `Show` instances.

**Comment by cdornan** [comment]
@cdepillabout great point and agreed! But I will probably settle on something that is at least pseudo-Haskell syntax.

**Comment by cdepillabout** [comment]
Thanks! That will make debugging a little easier.
