### ISSUE TITLE
Extract capture names from compiled PCRE regexes

### ISSUE THREAD

**Issue by 17dec** [iconnect/regex#153]
Is it possible to extract capture names from PCRE regexes? I tried the obvious approach, but that doesn't seem to work:
```
Prelude> import Text.RE.PCRE
Prelude Text.RE.PCRE> compileRegex "(?P<somename>.*)" >>= return . reCaptureNames
fromList []
```

**Comment by cdornan** [comment]
@17dec You will need to use the regex syntax for captures names:
```haskell
compileRegex  "${somename}(.*)" >>= return . reCaptureNames
```
This same syntax is available in regex for both TDFA/POSIX and PCRE back ends.

**Comment by 17dec** [comment]
Thanks for the quick reply. The non-standard syntax is unfortunate, but I can work with that.

Abusing this ticket for a related question: Since there is some custom processing of the regex going on before entering PCRE, is it a goal to still support PCRE-specific regex extensions? E.g. I've tried to use "(?i)${somename}(val)" to get local case-insensitivity, but that doesn't match any value I've tested it with.

**Comment by cdornan** [comment]
The intention is that each backend should support its own extensions. The preprocessor for implementing named-captures has been designed to not interfere with the PCRE extensions but there may be some interactions that I have not anticipated.

If you remove the regex named capture dos it work? (It should work either way and I would expect the regex named-captures to interfere.

You can also select case insensitivity [this way](http://regex.uk/re-tutorial.html):
```
[reMultilineInsensitive|${somename}(val)|]
```
or
```
[reMI|${somename}(val)|]
```
for short.

**Comment by 17dec** [comment]
Alright that's good to hear. I was confused since I couldn't get a regex with PCRE extensions to work in my codebase, but now that I'm trying out a small test case in GHCi everything seems to be working just fine, both with and without named captures.

Thanks for the help!

**Comment by cdornan** [comment]
Pleasure.
