### ISSUE TITLE
Version bounds need updates for GHC 8.8.1 stack nightly snapshots

### ISSUE THREAD

**Issue by vdukhovni** [iconnect/regex#173]
- hashable-1.3.0.0
- regex-base-0.94.0.0
- regex-pcre-builtin-0.95.1.1.8.43

**Comment by vdukhovni** [comment]
Also for the regex-with-pcre package:
- regex-base-0.94.0.0
- regex-pcre-builtin-0.95.1.1.8.43
- regex-tdfa-1.3.0

**Comment by Drezil** [comment]
As far as i see in my environment the dependency on `regex-tdfa-text` must be changed/dropped as this clashes with `regex-base-0.94.0.0` (both define instances for `Extract Text`. This was a breaking change in `regex-base-0.94.0.0`; see https://github.com/haskell-hvr/regex-base/blob/master/ChangeLog.md)

**Comment by vdukhovni** [comment]
I don't recall the exact set of dependency issues, but yes there may well be related issues in other packages. I filed tickets for some of the other packages also. Don't know what the final compatible combination will be.
I hope you're able to sort this out for this package.

**Comment by Drezil** [comment]
```
    Build-depends:
        array                >= 0.4
      , base                 >= 4        && <  5
      , base-compat          >= 0.6 && <0.12
      , bytestring           == 0.10.*
      , containers           >= 0.4
      , hashable             == 1.3.*
      , regex-base           == 0.94.*
      , regex-pcre-builtin   == 0.95.*
      , regex-tdfa           == 1.3.*
      , template-haskell     >= 2.7
      , text                 == 1.2.*
      , time                 >= 1.4.2
      , time-locale-compat   == 0.1.*
      , transformers         >= 0.2.2
      , unordered-containers == 0.2.*
      , utf8-string          >= 1
```
seems to compile further.

First error appearing gets fixed by
```
instance RegexLike Regex T.Text
instance RegexLike Regex LT.Text
```
but these orphan-instances should be in regex-base or something.

Next problem i found was in Text/RE/ZeInternals/NamedCaptures.lhs - here `error` gets used everywhere - which must not be due to the elimination of `fail` from Monad by the MonadFail-Proposal. So most of that file needs to be rewritten.. I have to see if i can make time for that ..
(That is file 21/47.. and now i give up hoping for a 'quick fix' .. -.-)

**Comment by vdukhovni** [comment]
> Next problem i found was in Text/RE/ZeInternals/NamedCaptures.lhs - here `error` gets used everywhere - which must not be due to the elimination of `fail` from Monad by the MonadFail-Proposal. So most of that file needs to be rewritten.. I have to see if i can make time for that ..

Thanks a bunch for looking into this, much appreciated and good luck!

**Comment by simonmichael** [comment]
Hi @cdornan.. do you think there could be a GHC 8.8 compatible release of regex soon ? It would help me a little in the hledger project (my Shake file uses regex, and it would be nice to have it build with the same GHC and deps as the main project).

**Comment by Drezil** [comment]
This is the last package preventing me from upgrading to 8.8.

i just dropped regex-tdfa-text & regex-pcre-text from the cabal-dependencies (as Text is now in regex-* and not in regex-*-text anymore; those packages got deprecated) and still run into the issue from the MonadFail-Proposal.

Got it compiling (see https://github.com/Drezil/regex/tree/issue_173 ), but that commit is only for ghc8.8+, because some CPP-pragmas are missing & i had to fiddle inside the cabal-file.
Some CPP-Expert need to clean that up.. -.- my expiriments just lead to ghc ignoring those lines :/

**Comment by cdornan** [comment]
@simonmichael @Drezil I am so sorry -- I am clearing another high priority backlog.

The earliest I can look at this is Friday 2019-01-17, which I will endeavour to do.

**Comment by Drezil** [comment]
@cdornan no problem :)
i am just eager to test with ghc8.8 .. but i won't deploy it in production without a stackage-lts anyway.. :)
Most of the work should be done - besides just making it compatible with ghc prior to 8.8.. which could mean a lot of CPP-Pragmas.. :/

**Comment by simonmichael** [comment]
Great news, thanks Chris. Not urgent.

**Comment by vdukhovni** [comment]
FWIW, Stackage now has GHC 8.8.2 snapshots and more of the dependencies are now included and working.  Indeed one of the key barriers appears to be MFP.

It is easy to create a (necessarily strict in the left argument of `>>=`) Monad which is basically `Identity` but with a MonadFail instance with `fail = error`.  I don't know whether that's the  right approach to take, or whether some other refactoring of the code would be more appropriate.

The key question is how/whether to maintain compatibility across multiple GHC releases. The simplest option is to simply say that that's what the older versions are for, and the next version would be 8.8.x and up only.  Otherwise the logic gets a bit more tricky.

**Comment by cdornan** [comment]
Thinks @vdukhovni &mdash; hopefully the `1.1.0.0` has done the trick.

@vdukhovni @Drezil @simonmichael `1.1.0.0` should work for GHC-8.8. Again, reaaly sorry for the delay.

**Comment by simonmichael** [comment]
Thanks @cdornan! https://github.com/simonmichael/hledger/issues/1090 closed.

**Comment by vdukhovni** [comment]
> Thinks @vdukhovni — hopefully the `1.1.0.0` has done the trick.
> 
> @vdukhovni @Drezil @simonmichael `1.1.0.0` should work for GHC-8.8. Again, reaaly sorry for the delay.

Indeed, much appreciated. My code now works with GHC 8.8.2.
