### ISSUE TITLE
regex>=1.0.1.4 incorrectly says it supports time 1.10

### ISSUE THREAD

**Issue by hsenag** [iconnect/regex#177]
In dd4fa940ab9a0b79107da8b0e7c00f4154651609 the upper bound on time was removed - I'm not sure if it was intentional given it's not mentioned in the commit message and #139 explicitly was about adding upper bounds.

The upshot is a build failure with time 1.10 and versions of regex>=1.0.1.4. The build failure may only be visible on Windows because the 'unix' package doesn't yet support time 1.10.

It'd be great if someone would make revisions on hackage to reinstate the upper bound (time 1.9 is fine so the bound could be `time<1.10`).

**Comment by hsenag** [comment]
FYI the actual build break is because `parseTime` was deprecated by 1.9 and actually removed in 1.10 - it should be replaced with `parseTimeM True`:
https://hackage.haskell.org/package/time-1.9/docs/Data-Time-Format.html#v:parseTime

**Comment by cdornan** [comment]
Switched to parseTimeM.
