### ISSUE TITLE
regex 1.1.0.0 incorrectly says it supports regex-tdfa 1.2

### ISSUE THREAD

**Issue by hsenag** [iconnect/regex#178]
If you try to build `regex` with `regex-tdfa` 1.2, there are errors about missing modules:

    cabal build --constraint 'regex-tdfa<1.3'

    Text\RE\ZeInternals\Replace.lhs:59:1: error:
        Could not load module `Text.Regex.TDFA.Text'
    Text\RE\ZeInternals\Replace.lhs:60:1: error:
        Could not load module `Text.Regex.TDFA.Text.Lazy'

As with #177 it'd be helpful if this could be revised on hackage.

**Comment by hsenag** [comment]
Update: regex-tda-1.3.0 doesn't work either. 1.3.1 does.

**Comment by cdornan** [comment]
regex-tdfa bound fixed.
