### ISSUE TITLE
finding the tutorials

### ISSUE THREAD

**Issue by juhp** [iconnect/regex#182]
FYI I was having trouble finding the tutorial(s):

http://tutorial.regex.uk/ goes to http://regex.uk/tutorial/ which seems to be broken (examples.regex.uk, etc too).

On github the tutorial.md links seem out of date:
maybe https://github.com/iconnect/regex/blob/master/lib/md/tutorial.md
should point to `examples/re-tutorial-*.lhs` now?

**Comment by cdornan** [comment]
I amke it that these links are working on the site -- please reopen if you are still having problems. (The links won't work in situ in the markdown).

**Comment by juhp** [comment]
They are working now thanks!
