### ISSUE TITLE
Type safe replacement templates

### ISSUE THREAD

**Issue by cdornan** [iconnect/regex#60]
Adam Bergmark asked on Haskell Cafe:

> Have you considered doing anything fancy to make capture groups safer to use? If i could get a compile error when i'm using the wrong number/wrongly named groups I'd be very excited.

**Comment by cdornan** [comment]
Just to be clear, that was @bergmark of course.

**Comment by cdornan** [comment]
I can see a reasonably safe way of providing type-safe replacement templates with named capture groups, which could be included in v1.0.0.0 so I will provide those and see how much remains to be done and what our options are once we have integrated those.

**Comment by bergmark** [comment]
Great stuff!
