### ISSUE TITLE
Make `regex` compatible w/ TH-less GHCs

### ISSUE THREAD

**Issue by hvr** [iconnect/regex#70]
I think `regex` can be made to avoid relying on `TemplateHaskell`+`QuasiQuotes` for recent GHC versions which provide the `TemplateHaskellQuotes` extension, which would have the benefit that GHCs which don't have interpreter support would be able to compile `regex`, and also the `TemplateHaskellQuotes` extension is considered "safe" under SafeHaskell, whereas `TemplateHaskell` is "unsafe".

There are currently 3 modules which rely on `TemplateHaskell`, 
 
 - `Text/RE/Options.lhs`
 - `Text/RE/TDFA/RE.hs`
 - `Text/RE/Internal/NamedCaptures.lhs`

The first two are trivial to make THQ-compatible; the 3rd one however makes use of `heredocs`, thereby actually executes TH code:

```hs
import           Text.Heredoc

scan :: String -> [Token]
scan = alex' match al oops
  where
    al :: [(Regex,Match String->Maybe Token)]
    al =
      [ mk [here|\$\{([^{}]+)\}\(|] $         ECap . Just . x_1
      , mk [here|\$\(|]             $ const $ ECap Nothing
      , mk [here|\(\?:|]            $ const   PGrp
      , mk [here|\(\?|]             $ const   PCap
      , mk [here|\(|]               $ const   Bra
      , mk [here|\\(.)|]            $         BS    . s2c . x_1
      , mk [here|(.)|]              $         Other . s2c . x_1
      ]
```

would it be possible to avoid using `heredocs` and thus avoid having to execute TH code?

**Comment by cdornan** [comment]
@hvr all looks quite do-able and expect it to be fixed in the next release (most likely over the weekend).

**Comment by hvr** [comment]
@cdornan great; fyi, as this is a bit non-obvious, here's an example how this was done in another package: https://github.com/ekmett/reflection/commit/d3c2d1361aa3dcf3aed70b591c5a6f28609e3bf5  (by now Hackage does actually accept the `HaskellTemplateQuotes` token)
