### ISSUE TITLE
regex-0.10.0.0 fails to compile

### ISSUE THREAD

**Issue by hvr** [iconnect/regex#88]
See http://hackage.haskell.org/package/regex-0.10.0.0/reports/ & http://104.239.175.197:8080/package/regex

```
Text/RE/TDFA/RE.hs:83:1: error:
    Failed to load interface for ‘Text.RE.Internal.SearchReplace’
    Perhaps you meant
      Text.RE.Types.SearchReplace (needs flag -package-key regex-0.9.0.0)
    Use -v to see a list of the files searched for.
```

**Comment by hvr** [comment]
After some investgation, I realise that `regex-0.10.0.0` is simply broken as it is missing a required `.hs` file; therefore I've blacklisted that release (see https://hackage.haskell.org/package/regex-0.10.0.0/revisions/); this way the cabal solver won't be allowed to pick up `regex-0.10.0.0`

**Comment by cdornan** [comment]
@hvr thanks -- I am now releasing 0.10.0.1. 

For my standard flow I have to upload the packages into Hackage and wait for everything to propogate before the sub-package tests will work. But with the reorganisation in 0.10.0.0 this needed manual testing.

**Comment by hvr** [comment]
@cdornan btw, are you using cabal's (via `cabal.project` files) or stack's ability (via `stack.yaml` files) to test multiple local (unreleased) packages against each other?

**Comment by cdornan** [comment]
@hvr neither at the moment -- I generate a combined single cabal file which I use for stack and cabal builds; the travis pipeline tests new releases through Hackage.

To test the sub-packages I am doing a manual install with cabal. It is on my list to sort this out &mdash; I guess it is top of the list now, probably with stack (that way it is easier to test all three compilers).

**Comment by hvr** [comment]
@cdornan hrm... now I'm curious: how is it easier to test all three compilers with stack than with https://github.com/hvr/multi-ghc-travis ? What's missing from my scripts to make it easier? :-)

**Comment by cdornan** [comment]
@hvr possibly nothing at all! It is just that I need it working with stack tooling which has the multi-compiler business working very well. 

So when I need to script test for cabal or stack I tend to choose stack. (I am used to everything working multi-compiler as for many years I have been using hub but I am migrating away from that now.)

I will check out multi-ghc-travis &mdash; thanks!

And thanks very much for your help!

**Comment by cdornan** [comment]
I have withdrawn the Hackage versions and am going to rebase the branch. In effect this issue is being closed in favour of the underlying issue #91 &mdash; proper testing being built into the release scripts.

**Comment by hvr** [comment]
Btw, please note that marking a release deprecated on https://hackage.haskell.org/package/regex/preferred/edit only soft-blacklists it. I.e. the cabal solver is not forbidden to pick such releases (the "preferred version mechanism" is more useful for releasing a new version which you don't want the solver to pick up automatically unless the user requests it or the solver has no other choice). If you want to really forbid the cabal solver to select a specific release you should retroactively add a `build-depends: base<0` via the `.cabal` revision mechanism.

**Comment by cdornan** [comment]
@hvr thanks for the tip &mdash; I have added the `base<0` constraint to all of the targets.
